---
title: "Quiz 7"
output: html_document
date: "2024-10-06"
---

```{r}
library(tidyverse)
```


```{r}
x = data.frame(
  Subject = letters[1:8],
  Treatment_1 = c(8.4, 12.8, 9.6, 9.8, 8.4, 8.6, 8.9, 7.9),
  Treatment_2 = c(9.4, 15.2, 9.1, 8.8, 8.2, 9.9, 9, 8.1),
  Treatment_3 = c(9.8, 12.9, 11.2, 9.9, 8.5, 9.8, 9.2, 8.2),
  Treatment_4 = c(12.2, 14.4, 9.8, 12, 8.5, 10.9, 10.4, 10)
)
```

```{r}
# Reshape the data to long format
long_data <- x %>% pivot_longer(
  cols = -Subject,
  names_to = "Treatment",
  values_to = "ClottingTime"
)

# Convert Treatment to a factor
long_data$Treatment <- as.factor(long_data$Treatment)

# Perform ANOVA
anova_result <- aov(ClottingTime ~ Treatment, data = long_data)
summary(anova_result)
```



```{r}
dplyr::glimpse(npk) 
```

```{r}
# Load necessary library
library(dplyr)

# Convert factors to make sure they are in the correct format
npk$N <- as.factor(npk$N)
npk$P <- as.factor(npk$P)
npk$block <- as.factor(npk$block)
# Perform the ANOVA including block, nitrogen, phosphate and their interaction
npk_aov <- aov(yield ~ block + N + P + N:P, data = npk)

# Display the summary of the ANOVA model to see the p-values
summary(npk_aov)

```

