---
title: "Lab 02-Cereal"
date: "2024-08-08"
author: "Ellen Ebdrup"
output: 
  html_document: 
    ### IMPORTANT ###
    # self_contained: true # Creates a single HTML file as output
    code_folding: show # Code folding; allows you to show/hide code chunks
    ### USEFUL ###
    code_download: true # Includes a menu to download the code file
    ### OPTIONAL ###
    df_print: paged # Sets how dataframes are automatically printed
    theme: readable # Controls the font, colours, etc.
    toc: true # (Useful) Creates a table of contents!
    toc_float: true # table of contents at the side
    number_sections: false # (Optional) Puts numbers next to heading/subheadings
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)

path = "https://github.com/DATA2002/data/raw/master/Cereal.csv"
cereal = readr::read_csv(path, na = "-1")
dplyr::glimpse(cereal)
```

Difficult to plot:
When you have a lot of variables that you want to plot on the same plot.
Solution: dimensionality reduction

```{r}
# 1. Histogram of Calories
ggplot(cereal, aes(x = calories)) +
  geom_histogram(binwidth = 10, fill = "blue", color = "black") +
  labs(title = "Distribution of Calories in Cereals", x = "Calories", y = "Frequency")
```

```{r}
# 2. Boxplot of Sugars by Manufacturer
ggplot(cereal, aes(x = mfr, y = sugars, fill = mfr)) +
  geom_boxplot() +
  labs(title = "Sugars Content by Manufacturer", x = "Manufacturer", y = "Sugars (g)")
```

```{r}
# 3. Scatter Plot of Rating vs. Calories
ggplot(cereal, aes(x = calories, y = rating)) +
  geom_point(color = "red") +
  geom_smooth(method = "lm", color = "blue") +
  labs(title = "Rating vs. Calories", x = "Calories", y = "Rating")
```


```{r}
# 4. Bar Plot of Cereal Types
ggplot(cereal, aes(x = type, fill = type)) +
  geom_bar() +
  labs(title = "Count of Different Cereal Types", x = "Type", y = "Count")
```








